install.packages("caret")
library("caret")
install.packages( 'caret' )
library( 'caret' )
install.packages( "pacman" )
library( "pacman" )
pacman::p_load(dplyr, htmltools, leaflet, leaflet.extras, leaflet.minicharts, leafpop, plotly, rgdal, sf, tidyr)
install.packages( " iris " )
library( " iris " )
featurePlot(x=iris[, 1:4], iris= $Species)
install.packages("githubinstall")
library(githubinstall)
view(iris)
install.packages("ggplot2")
str(DATA_FRAME_METODOLOGIA_TOPICOS_ESPECIAIS_RSU_PERNAMBUCO_ajustado_ao_R)	
DATA_FRAME_METODOLOGIA_TOPICOS_ESPECIAIS_RSU_PERNAMBUCO_ajustado_ao_R <- as.factor(DATA_FRAME_METODOLOGIA_TOPICOS_ESPECIAIS_RSU_PERNAMBUCO_ajustado_ao_R)   
str(DATARSU)   
DATARSU <- as.factor(DATARSU)
DATARSU <- as.factor(municipio)
DATARSU$Municipio <- as.factor(DATARSU$Municipio)
plot(DATARSU)
install.packages("fBasics")
table(DATARSU$Populacao)
prop.table(table(DATARSU$Populacao))
mean(DATARSU$Populacao)
median(DATARSU$Populacao)
quantile(DATARSU$Populacao, probs = 0.75)
quantile(DATARSU$Populacao, probs = 0.95)
boxplot(DATARSU$Populacao)
sd(DATARSU$Populacao)
plot(DATARSU$Populacao)
summary(DATARSU)
pacman::p_load(fbasicStats)
install.packages("statsr")
summary(DATARSU)
install.packages("fBasics")

install.packages("pacman")
pacman::p_load(fBasics)
DATARSU <- as.factor('DATARSU')
DATARSU <- as.factor(municipio)
DATARSU$Municipio <- as.factor(DATARSU$Municipio)
prop.table(table(DATARSU$Populacao))
mean(DATARSU$Populacao)
median(DATARSU$Populacao)
quantile(DATARSU$Populacao, probs = 0.75)
quantile(DATARSU$Populacao, probs = 0.95)
boxplot(DATARSU$Populacao)
sd(DATARSU$Populacao)
plot(DATARSU$Populacao)
summary(DATARSU)

DATARSU$Municipio <- as.factor(DATARSU$Municipio)
summary(DATARSU)
str(datarsu)
mean(DATARSU$Populacao)
str(DATARSU)
View(DATARSU)
plot(DATARSU)
DATARSU$Municipio <- as.factor(DATARSU$Municipio)
summary(DATARSU)
str(datarsu)
mean(DATARSU$Populacao)
str(DATARSU)
View(DATARSU)
plot(DATARSU)
median(DATARSU$Populacao)
quantile(DATARSU$Populacao, probs = 0.75)
quantile(DATARSU$Populacao, probs = 0.95)
boxplot(DATARSU$Populacao)
sd(DATARSU$Populacao)
plot(DATARSU$Populacao)
boxplot(DATARSU$Influencia_grupos_interesse)
